from typing import List

from llm_github_models._types import ChatModelSpec

CHAT_MODELS: List[ChatModelSpec] = [
    ChatModelSpec(
        llm_id="ai21-jamba-1.5-large",
        github_id="ai21-labs/ai21-jamba-1.5-large",
        name="AI21 Jamba 1.5 Large",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/AI21-Jamba-1.5-Large"],
    ),
    ChatModelSpec(
        llm_id="ai21-jamba-1.5-mini",
        github_id="ai21-labs/ai21-jamba-1.5-mini",
        name="AI21 Jamba 1.5 Mini",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/AI21-Jamba-1.5-Mini"],
    ),
    ChatModelSpec(
        llm_id="cohere-command-a",
        github_id="cohere/cohere-command-a",
        name="Cohere Command A",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Cohere-Command-A"],
    ),
    ChatModelSpec(
        llm_id="cohere-command-r-08-2024",
        github_id="cohere/cohere-command-r-08-2024",
        name="Cohere Command R 08-2024",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Cohere-Command-R-08-2024"],
    ),
    ChatModelSpec(
        llm_id="cohere-command-r-plus-08-2024",
        github_id="cohere/cohere-command-r-plus-08-2024",
        name="Cohere Command R+ 08-2024",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Cohere-Command-R+-08-2024"],
    ),
    ChatModelSpec(
        llm_id="jais-30b-chat",
        github_id="core42/jais-30b-chat",
        name="JAIS 30b Chat",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/JAIS-30b-Chat"],
    ),
    ChatModelSpec(
        llm_id="deepseek-r1",
        github_id="deepseek/deepseek-r1",
        name="DeepSeek-R1",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/DeepSeek-R1"],
    ),
    ChatModelSpec(
        llm_id="deepseek-r1-0528",
        github_id="deepseek/deepseek-r1-0528",
        name="DeepSeek-R1-0528",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/DeepSeek-R1-0528"],
    ),
    ChatModelSpec(
        llm_id="deepseek-v3-0324",
        github_id="deepseek/deepseek-v3-0324",
        name="DeepSeek-V3-0324",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/DeepSeek-V3-0324"],
    ),
    ChatModelSpec(
        llm_id="llama-3.2-11b-vision-instruct",
        github_id="meta/llama-3.2-11b-vision-instruct",
        name="Llama-3.2-11B-Vision-Instruct",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text", "image", "audio"],
        supported_output_modalities=["text"],
        aliases=["github/Llama-3.2-11B-Vision-Instruct"],
    ),
    ChatModelSpec(
        llm_id="llama-3.2-90b-vision-instruct",
        github_id="meta/llama-3.2-90b-vision-instruct",
        name="Llama-3.2-90B-Vision-Instruct",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text", "image", "audio"],
        supported_output_modalities=["text"],
        aliases=["github/Llama-3.2-90B-Vision-Instruct"],
    ),
    ChatModelSpec(
        llm_id="llama-3.3-70b-instruct",
        github_id="meta/llama-3.3-70b-instruct",
        name="Llama-3.3-70B-Instruct",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Llama-3.3-70B-Instruct"],
    ),
    ChatModelSpec(
        llm_id="llama-4-maverick-17b-128e-instruct-fp8",
        github_id="meta/llama-4-maverick-17b-128e-instruct-fp8",
        name="Llama 4 Maverick 17B 128E Instruct FP8",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/Llama-4-Maverick-17B-128E-Instruct-FP8"],
    ),
    ChatModelSpec(
        llm_id="llama-4-scout-17b-16e-instruct",
        github_id="meta/llama-4-scout-17b-16e-instruct",
        name="Llama 4 Scout 17B 16E Instruct",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/Llama-4-Scout-17B-16E-Instruct"],
    ),
    ChatModelSpec(
        llm_id="meta-llama-3.1-405b-instruct",
        github_id="meta/meta-llama-3.1-405b-instruct",
        name="Meta-Llama-3.1-405B-Instruct",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Meta-Llama-3.1-405B-Instruct"],
    ),
    ChatModelSpec(
        llm_id="meta-llama-3.1-8b-instruct",
        github_id="meta/meta-llama-3.1-8b-instruct",
        name="Meta-Llama-3.1-8B-Instruct",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Meta-Llama-3.1-8B-Instruct"],
    ),
    ChatModelSpec(
        llm_id="mai-ds-r1",
        github_id="microsoft/mai-ds-r1",
        name="MAI-DS-R1",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/MAI-DS-R1"],
    ),
    ChatModelSpec(
        llm_id="phi-3-medium-128k-instruct",
        github_id="microsoft/phi-3-medium-128k-instruct",
        name="Phi-3-medium instruct (128k)",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-3-medium-instruct-(128k)"],
    ),
    ChatModelSpec(
        llm_id="phi-3-medium-4k-instruct",
        github_id="microsoft/phi-3-medium-4k-instruct",
        name="Phi-3-medium instruct (4k)",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-3-medium-instruct-(4k)"],
    ),
    ChatModelSpec(
        llm_id="phi-3-mini-128k-instruct",
        github_id="microsoft/phi-3-mini-128k-instruct",
        name="Phi-3-mini instruct (128k)",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-3-mini-instruct-(128k)"],
    ),
    ChatModelSpec(
        llm_id="phi-3-mini-4k-instruct",
        github_id="microsoft/phi-3-mini-4k-instruct",
        name="Phi-3-mini instruct (4k)",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-3-mini-instruct-(4k)"],
    ),
    ChatModelSpec(
        llm_id="phi-3-small-128k-instruct",
        github_id="microsoft/phi-3-small-128k-instruct",
        name="Phi-3-small instruct (128k)",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-3-small-instruct-(128k)"],
    ),
    ChatModelSpec(
        llm_id="phi-3-small-8k-instruct",
        github_id="microsoft/phi-3-small-8k-instruct",
        name="Phi-3-small instruct (8k)",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-3-small-instruct-(8k)"],
    ),
    ChatModelSpec(
        llm_id="phi-3.5-mini-instruct",
        github_id="microsoft/phi-3.5-mini-instruct",
        name="Phi-3.5-mini instruct (128k)",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-3.5-mini-instruct-(128k)"],
    ),
    ChatModelSpec(
        llm_id="phi-3.5-moe-instruct",
        github_id="microsoft/phi-3.5-moe-instruct",
        name="Phi-3.5-MoE instruct (128k)",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-3.5-MoE-instruct-(128k)"],
    ),
    ChatModelSpec(
        llm_id="phi-4",
        github_id="microsoft/phi-4",
        name="Phi-4",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-4"],
    ),
    ChatModelSpec(
        llm_id="phi-4-mini-instruct",
        github_id="microsoft/phi-4-mini-instruct",
        name="Phi-4-mini-instruct",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-4-mini-instruct"],
    ),
    ChatModelSpec(
        llm_id="phi-4-mini-reasoning",
        github_id="microsoft/phi-4-mini-reasoning",
        name="Phi-4-mini-reasoning",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-4-mini-reasoning"],
    ),
    ChatModelSpec(
        llm_id="phi-4-multimodal-instruct",
        github_id="microsoft/phi-4-multimodal-instruct",
        name="Phi-4-multimodal-instruct",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["audio", "image", "text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-4-multimodal-instruct"],
    ),
    ChatModelSpec(
        llm_id="phi-4-reasoning",
        github_id="microsoft/phi-4-reasoning",
        name="Phi-4-reasoning",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Phi-4-reasoning"],
    ),
    ChatModelSpec(
        llm_id="codestral-2501",
        github_id="mistral-ai/codestral-2501",
        name="Codestral 25.01",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Codestral-25.01"],
    ),
    ChatModelSpec(
        llm_id="ministral-3b",
        github_id="mistral-ai/ministral-3b",
        name="Ministral 3B",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Ministral-3B"],
    ),
    ChatModelSpec(
        llm_id="mistral-large-2411",
        github_id="mistral-ai/mistral-large-2411",
        name="Mistral Large 24.11",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Mistral-Large-24.11"],
    ),
    ChatModelSpec(
        llm_id="mistral-medium-2505",
        github_id="mistral-ai/mistral-medium-2505",
        name="Mistral Medium 3 (25.05)",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/Mistral-Medium-3-(25.05)"],
    ),
    ChatModelSpec(
        llm_id="mistral-nemo",
        github_id="mistral-ai/mistral-nemo",
        name="Mistral Nemo",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Mistral-Nemo"],
    ),
    ChatModelSpec(
        llm_id="mistral-small-2503",
        github_id="mistral-ai/mistral-small-2503",
        name="Mistral Small 3.1",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/Mistral-Small-3.1"],
    ),
    ChatModelSpec(
        llm_id="gpt-4.1",
        github_id="openai/gpt-4.1",
        name="OpenAI GPT-4.1",
        supports_schemas=True,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-GPT-4.1"],
    ),
    ChatModelSpec(
        llm_id="gpt-4.1-mini",
        github_id="openai/gpt-4.1-mini",
        name="OpenAI GPT-4.1-mini",
        supports_schemas=True,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-GPT-4.1-mini"],
    ),
    ChatModelSpec(
        llm_id="gpt-4.1-nano",
        github_id="openai/gpt-4.1-nano",
        name="OpenAI GPT-4.1-nano",
        supports_schemas=True,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-GPT-4.1-nano"],
    ),
    ChatModelSpec(
        llm_id="gpt-4o",
        github_id="openai/gpt-4o",
        name="OpenAI GPT-4o",
        supports_schemas=True,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image", "audio"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-GPT-4o"],
    ),
    ChatModelSpec(
        llm_id="gpt-4o-mini",
        github_id="openai/gpt-4o-mini",
        name="OpenAI GPT-4o mini",
        supports_schemas=True,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image", "audio"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-GPT-4o-mini"],
    ),
    ChatModelSpec(
        llm_id="gpt-5",
        github_id="openai/gpt-5",
        name="OpenAI gpt-5",
        supports_schemas=True,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-gpt-5"],
    ),
    ChatModelSpec(
        llm_id="gpt-5-chat",
        github_id="openai/gpt-5-chat",
        name="OpenAI gpt-5-chat (preview)",
        supports_schemas=False,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-gpt-5-chat-(preview)"],
    ),
    ChatModelSpec(
        llm_id="gpt-5-mini",
        github_id="openai/gpt-5-mini",
        name="OpenAI gpt-5-mini",
        supports_schemas=True,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-gpt-5-mini"],
    ),
    ChatModelSpec(
        llm_id="gpt-5-nano",
        github_id="openai/gpt-5-nano",
        name="OpenAI gpt-5-nano",
        supports_schemas=True,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-gpt-5-nano"],
    ),
    ChatModelSpec(
        llm_id="o1",
        github_id="openai/o1",
        name="OpenAI o1",
        supports_schemas=True,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-o1"],
    ),
    ChatModelSpec(
        llm_id="o1-mini",
        github_id="openai/o1-mini",
        name="OpenAI o1-mini",
        supports_schemas=True,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-o1-mini"],
    ),
    ChatModelSpec(
        llm_id="o1-preview",
        github_id="openai/o1-preview",
        name="OpenAI o1-preview",
        supports_schemas=False,
        supports_streaming=False,
        supports_tools=False,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-o1-preview"],
    ),
    ChatModelSpec(
        llm_id="o3",
        github_id="openai/o3",
        name="OpenAI o3",
        supports_schemas=False,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-o3"],
    ),
    ChatModelSpec(
        llm_id="o3-mini",
        github_id="openai/o3-mini",
        name="OpenAI o3-mini",
        supports_schemas=True,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-o3-mini"],
    ),
    ChatModelSpec(
        llm_id="o4-mini",
        github_id="openai/o4-mini",
        name="OpenAI o4-mini",
        supports_schemas=True,
        supports_streaming=True,
        supports_tools=True,
        supported_input_modalities=["text", "image"],
        supported_output_modalities=["text"],
        aliases=["github/OpenAI-o4-mini"],
    ),
    ChatModelSpec(
        llm_id="grok-3",
        github_id="xai/grok-3",
        name="Grok 3",
        supports_schemas=True,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Grok-3"],
    ),
    ChatModelSpec(
        llm_id="grok-3-mini",
        github_id="xai/grok-3-mini",
        name="Grok 3 Mini",
        supports_schemas=True,
        supports_streaming=False,
        supports_tools=True,
        supported_input_modalities=["text"],
        supported_output_modalities=["text"],
        aliases=["github/Grok-3-Mini"],
    ),
]
